import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { Provider } from "@/components/providers";
import GlobalContext from "@/context";
import Navbar from "@/components/shared/navbar";
import { Toaster } from "@/components/ui/toaster";


const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Netflix Web Clone",
  description: "Generated by c Next TMDB MongooDB ",
  icons:"/netflix.png"
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Provider attribute="class"  defaultTheme="dark" enableSystem disableTransitionOnChange >
        <GlobalContext>
          <Navbar/>
            {children}
            <Toaster/>
          </GlobalContext>
        </Provider>
      </body>
    </html>
  );
}
